server:
  port: 8081
spring:
  datasource:
    # database connect pool
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 # 数据库索引
    timeout: 1800000 # 连接超时时间
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数
        max-wait: -1 # 最大阻塞等待时间
        max-idle: 5 # 最大空闲连接
        min-idle: 0 # 最小空闲连接